version: '3.4'

networks:
  Microservices:  # Nome personalizado para a rede
    driver: bridge

services:
  microservicesgateway:
    image: ${DOCKER_REGISTRY-}microservicesgateway
    build:
      context: .
      dockerfile: MicroservicesGateway/Dockerfile
    ports:
      - "9090:443"  # Mapeie para a porta 443 para HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80  # Specify HTTPS and HTTP URLs
    networks:
      - Microservices
    volumes:
      - ./etc/RSA:/etc/RSA
      - ./etc/Logs:/etc/Logs  
      - ./etc/firebase:/etc/firebase  
  
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
      - "9091:443"  # Mapeie para a porta 443 para HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80  # Specify HTTPS and HTTP URLs
    networks:
      - Microservices
    volumes:
      - ./etc/RSA:/etc/RSA
      - ./etc/Logs:/etc/Logs  
      - ./etc/firebase:/etc/firebase  
    labels:
      com.docker.compose.network: Microservices
      com.docker.compose.project: Microservices
      com.docker.compose.version: 2.23.0

  eventsapi:
    image: ${DOCKER_REGISTRY-}eventsapi
    build:
      context: .
      dockerfile: EventsAPI/Dockerfile
    ports:
      - "9093:443"  # Mapeie para a porta 443 para HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80  # Specify HTTPS and HTTP URLs
    networks:
      - Microservices
    volumes:
      - ./etc/RSA:/etc/RSA
      - ./etc/Logs:/etc/Logs
      - ./etc/firebase:/etc/firebase  

  userdetailsapi:
    image: ${DOCKER_REGISTRY-}userdetailsapi
    build:
      context: .
      dockerfile: UserDetailsAPI/Dockerfile
    ports:
      - "9094:443"  # Mapeie para a porta 443 para HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80  # Specify HTTPS and HTTP URLs
    networks:
      - Microservices
    volumes:
      - ./etc/RSA:/etc/RSA
      - ./etc/Logs:/etc/Logs
      - ./etc/firebase:/etc/firebase  

